# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chol_solve <- function(M, V) {
    .Call(`_gigg_chol_solve`, M, V)
}

rgig_cpp <- function(chi, psi, lambda) {
    .Call(`_gigg_rgig_cpp`, chi, psi, lambda)
}

quick_solve <- function(XtX_inv, D_pos, vec_draw) {
    .Call(`_gigg_quick_solve`, XtX_inv, D_pos, vec_draw)
}

gigg_fixed_gibbs_sampler <- function(X, C, Y, grp_idx, grp_size, grp_size_cs, alpha_inits, beta_inits, lambda_sq_inits, gamma_sq_inits, eta_inits, p, q, tau_sq_init = 1, sigma_sq_init = 1, nu_init = 1, n_burn_in = 500L, n_samples = 1000L, n_thin = 1L, stable_const = 1e-07, verbose = TRUE, btrick = FALSE, stable_solve = FALSE) {
    .Call(`_gigg_gigg_fixed_gibbs_sampler`, X, C, Y, grp_idx, grp_size, grp_size_cs, alpha_inits, beta_inits, lambda_sq_inits, gamma_sq_inits, eta_inits, p, q, tau_sq_init, sigma_sq_init, nu_init, n_burn_in, n_samples, n_thin, stable_const, verbose, btrick, stable_solve)
}

#' Inverse digamma function.
#'
#' Evaluate the inverse digamma function.
#' @param y value to evaluate the inverse digamma function at.
#' @param precision default = 1e-08.
#' @return Numeric inverse digamma value.
digamma_inv <- function(y, precision = 1e-08) {
    .Call(`_gigg_digamma_inv`, y, precision)
}

gigg_mmle_gibbs_sampler <- function(X, C, Y, grp_idx, grp_size, grp_size_cs, alpha_inits, beta_inits, lambda_sq_inits, gamma_sq_inits, eta_inits, p_inits, q_inits, tau_sq_init = 1, sigma_sq_init = 1, nu_init = 1, n_burn_in = 500L, n_samples = 1000L, n_thin = 1L, stable_const = 1e-07, verbose = TRUE, btrick = FALSE, stable_solve = FALSE) {
    .Call(`_gigg_gigg_mmle_gibbs_sampler`, X, C, Y, grp_idx, grp_size, grp_size_cs, alpha_inits, beta_inits, lambda_sq_inits, gamma_sq_inits, eta_inits, p_inits, q_inits, tau_sq_init, sigma_sq_init, nu_init, n_burn_in, n_samples, n_thin, stable_const, verbose, btrick, stable_solve)
}

